### ISSUE TITLE
Website 

### ISSUE THREAD

**Issue by diwas7777** [diwas7777/LinkTree#6]
Can anyone help me make a website for this github repo 

For template you can visit the website in homepage and i want it to update automatically when someone adds a new file instead of doing it manually

**Comment by utkarshgoel10** [comment]
@diwas7777 
Hey! 
We can perform this task using javascript, I have an idea on how to make it work.
I want to try that idea, so could you assign this to me.

**Comment by diwas7777** [comment]
yes

**Comment by diwas7777** [comment]
@utkarshgoel10

**Comment by diwas7777** [comment]
@utkarshgoel10 assigned

**Comment by diwas7777** [comment]
@utkarshgoel10 can you please reply for confirmation

**Comment by utkarshgoel10** [comment]
Yes @diwas7777  I'm working

**Comment by ghost** [comment]
@utkarshgoel10 is there any way to make update website automatically like in template website and new folders that is added to github and display it accordingly for users to choose to view

**Comment by utkarshgoel10** [comment]
@diwas7777 Okay, let me check once.
I've also dm you.

**Comment by ghost** [comment]
@utkarshgoel10 okay

**Comment by utkarshgoel10** [comment]
Is this issue resolved?
